version: 2.1

orbs:
  gh-pages: sugarshin/gh-pages@0.0.6

defaults: &defaults
  working_directory: ~/repo
  docker:
    - image: circleci/node:latest


jobs:
  build:
    <<: *defaults
    steps:
      - checkout
      - run: npm ci
      - run: npm run build
      - run: npm run build-storybook
      - persist_to_workspace:
          root: ~/repo
          paths: .
  gh-pages:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/repo
      - run: mkdir ~/.ssh && touch ~/.ssh/known_hosts
      - run: ssh-keyscan github.com >> ~/.ssh/known_hosts
      - gh-pages/deploy:
          build-dir: storybook-static
          ssh-fingerprints: '52:13:49:84:36:e7:20:b0:fc:26:d4:5d:0a:b9:fa:fa'
  publish-npm:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/repo
      - run:
          name: Authenticate with registry
          command: echo “//registry.npmjs.org/:_authToken=$NPM_TOKEN > ~/repo/.npmrc
      - run:
          name: Publish package
          command: ./node_modules/.bin/lerna publish --no-git-reset --yes from-git

workflows:
  version: 2
  build_and_publish:
    jobs:
      - build:
          filters:
            branches:
              only: master
      - gh-pages:
          requires:
            - build
      - publish-npm:
          requires:
            - build
  build:
    jobs:
      - build:
          filters:
            branches:
              ignore: master
