orbs:
  gh-pages: sugarshin/gh-pages@0.0.6

version: 2.1
jobs:
  build:
    docker:
      - image: node:latest
    steps:
      - checkout
      - run: npm install
      - run: npm run build
      - run: npm run build-storybook
      - gh-pages/deploy:
          build-dir: storybook-static