version: 2.1

orbs:
  gh-pages: sugarshin/gh-pages@0.0.6

defaults: &defaults
  working_directory: ~/repo
  docker:
    - image: circleci/node:latest-browsers


jobs:
  build:
    <<: *defaults
    steps:
      - checkout
      - run: npm ci
      - run: npm run build
      - run: npm run build-storybook
      - persist_to_workspace:
          root: ~/repo
          paths: .
  test:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/repo
      - run: google-chrome --version
      - run:
          name: Run all Browser Tests
          command: npm run test
      - store_test_results:
          path: ./reports
      - store_artifacts:
          path: ./reports
  gh-pages:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/repo
      - run: mkdir ~/.ssh && touch ~/.ssh/known_hosts
      - run: ssh-keyscan github.com >> ~/.ssh/known_hosts
      - gh-pages/deploy:
          build-dir: storybook-static
          ssh-fingerprints: '52:13:49:84:36:e7:20:b0:fc:26:d4:5d:0a:b9:fa:fa'
  publish-npm:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/repo
      - run:
          name: Authenticate with registry
          command: npm run login
      - run:
          name: Publish package
          command: ./node_modules/.bin/lerna publish --yes from-package
      - run:
          name: purge CDN cache for confirmation component
          command: curl https://purge.jsdelivr.net/npm/wertgarantie-confirmation@2/dist/confirmation.min.js
      - run:
          name: purge CDN cache for selection pop up component
          command: curl https://purge.jsdelivr.net/npm/wertgarantie-selection-popup@2/dist/selection-popup.min.js
      - run:
          name: purge CDN cache for embedded selection component
          command: curl https://purge.jsdelivr.net/npm/wertgarantie-embedded-selection@0/dist/selection-embedded.min.js
      - run:
          name: purge CDN cache for rating component
          command: curl https://purge.jsdelivr.net/npm/wertgarantie-rating@2/dist/rating.min.js
      - run:
          name: purge CDN cache for after sales component
          command: curl https://purge.jsdelivr.net/npm/wertgarantie-after-sales@1/dist/after-sales.min.js
      - run:
          name: purge CDN cache for landing page component
          command: curl https://purge.jsdelivr.net/npm/wertgarantie-landing-page@0/dist/landing-page.min.js
      - run:
          name: purge CDN cache for information pop up component
          command: curl https://purge.jsdelivr.net/npm/wertgarantie-information-popup@1/dist/information-popup.min.js
workflows:
  version: 2
  build_and_publish:
    jobs:
      - build:
          filters:
            branches:
              only: master
      - test:
          requires:
            - build
      - gh-pages:
          requires:
            - build
            - test
      - publish-npm:
          requires:
            - build
            - test
  build:
    jobs:
      - build:
          filters:
            branches:
              ignore: master
