orbs:
  gh-pages: sugarshin/gh-pages@0.0.6

version: 2.1
jobs:
  build:
    docker:
      - image: node:latest
    steps:
      - checkout
      - run: npm install
      - run: npm run build
      - run: npm run build-storybook
      - gh-pages/deploy:
          build-dir: storybook-static
          ssh-fingerprints: '52:13:49:84:36:e7:20:b0:fc:26:d4:5d:0a:b9:fa:fa'